DROP TABLE IF EXISTS history;
CREATE TABLE history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  operation TEXT NOT NULL,
  left_operand DECIMAL NOT NULL,
  right_operand DECIMAL NOT NULL,
  result DECIMAL NOT NULL
);